### ISSUE TITLE
Experiment reproducibility

### ISSUE THREAD

**Issue by vodp** [cranedroesch/ML_yield_ERL#1]
Hi,

Would you mind updating data files used in  your code? That would be a better starting point to understand your method.

Cheers,

**Comment by cranedroesch** [comment]
Hello, the data is too big for github.  While it's all from public sources, I didn't use scripts to ETL all of it, so you'll need the actual files that I've got.  I'm happy to share the dropbox folder that it lives in.  Shoot me an email at andrewcd@gmail.com

**Comment by cranedroesch** [comment]
Anyone who'd like the data: please just send me a note.  Preferably one that tells me a bit about what you're working on!

**Comment by ken-del** [comment]
Hi, first of all thans alot for the panelNNET :) 
I am trying to predict the tourism activity using the panelNNET, but  I'm stuck in some parts.
Therefore, I thought of solving the places where I was stuck in the code by going over the data set you used in the article.
Since you used a large data set and taken from different places, I had difficulties to create it myself. 

I saw message at github.com  that "Anyone who'd like the data: please just send me a note". 

Therefore, if appropriate, can you send the data set you specified in the study?

Semiparametric panel data models using neural networks ( or Machine learning methods for crop yield prediction and climate change) 

Thanks in advance,
